api_version = "2026-04"

[[extensions]]
name = "Quiz History"
handle = "quiz-history"
type = "ui_extension"
uid = "quiz-history-extension"

[[extensions.targeting]]
module = "./src/QuizHistoryBlock.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
api_access = true
network_access = true

